simulate:
  params: &default_simulate_params
    n: [100, 1000, 10_000, 100_000]
    k: [2, 4, 8, 16]
    beta: [0.0, 0.5, 1.5, 2.5, 5.0, 10.0, !!float .inf]
    logspace: [True, False]
    kbar: 10
    n_rep: 10
  n_jobs: &default_n_jobs "${oc.decode:${oc.env:GRGG_N_JOBS,10}}"
  spherical:
    seed: 421765311
    n_jobs: *default_n_jobs
    params:
      <<: *default_simulate_params
